### PR TITLE
Update part 3

### PR DESCRIPTION
**Pull request by ludelafo**
- [x] Restructure `<chapter_name>/index.md` to `<chapter_name>.md`
- [x] Update "State of MLOps process" with new checkpoint from part 2
- [x] Update cml report with image branch name title (see #111)
- [x] Add activate venv warning (see #116)
- [ ] Update command outputs from checkpoint generator
- [ ] Update cleanup section with GCP Artifact Registry
- [ ] Update `actions.yaml` for the checkpoint generator with commands of chapters 11-15

### CODE REVIEW

**Comment by ludelafo** [comment]
The pipeline is failing at the moment because I need to update my credit cards information on Google Cloud.

We might need to find a more sustainable way to host the demo on GCP with a Billing account for the team?

What do you think?

**Comment by rmarquis** [comment]
Definitely a good idea. The current setup of using a personal account is very annoying. Who should we contact to get this rolling? I'm only afraid of the bureaucratic mess to get a team billing account, but the earlier we sort it out the better,

**Review by rmarquis — APPROVED** [review]
I've done several passes on this branches the past few weeks (the latest time yesterday). There's still a few todo here and there in the latter chapters to sort out, but we can fix this gradually. Good to merge as of now.

**Comment by ludelafo** [comment]
> Definitely a good idea. The current setup of using a personal account is very annoying. Who should we contact to get this rolling? I'm only afraid of the bureaucratic mess to get a team billing account, but the earlier we sort it out the better,

I guess we should discuss this with @bchapuis.

**Pull request merged**
